
services:
  api_db:
    hostname: api_db
    image: postgres:17-alpine
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  go-api:
    container_name: go-api
    image: gp-api-task
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - "api_db"

volumes:
  pgdata: {}